name:                rivika
version:             0.1.0.0
github:              "git@github.com:FP-Modeling/rivika.git"
license:             MIT
author:              "Eduardo Lemos Rocha"
maintainer:          "dudulr10@gmail.com"
copyright:           "2022 EduardoLR10"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/FP-Modeling/rivika/blob/main/README.md>

dependencies:
- base >= 4.7 && < 5
- mtl >= 1.1.0.2
- array >= 0.3.0.0
- criterion
- criterion-measurement

library:
  source-dirs: src

executables:
  rivika-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    dependencies:
    - rivika
