name:                mivika
version:             0.1.0.0
github:              "githubuser/mivika"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mivika#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 1.1.0.2
- array >= 0.3.0.0

library:
  source-dirs: src

executables:
  mivika-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    dependencies:
    - mivika

tests:
  mivika-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mivika
